global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'market-data-core'
    static_configs:
      - targets: ['md-core:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    
  - job_name: 'market-data-ui'
    static_configs:
      - targets: ['ui:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s